const recipient='rortegarcia@gmail.com';
const titles={'cuentos-garcia-marquez':'Taller de cuentos de Gabriel García Márquez','cuentos-clarice-lispector':'Taller de cuentos de Clarice Lispector','garcia-lorca':'Taller García Lorca','cien-anos-de-soledad':'Taller Cien años de soledad'};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
const b64=bytes=>btoa(String.fromCharCode(...new Uint8Array(bytes))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
async function hmac(key,data){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(key),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64(await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(data)));}
async function api(env,path,body,id){return fetch('https://api.resend.com'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+env.RESEND_API_KEY,'Content-Type':'application/json',...(id?{'Idempotency-Key':id}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(12000)});}
async function receipt(env,id){const value=id+'.'+(Math.floor(Date.now()/1000)+86400);return value+'.'+await hmac(env.REGISTRATION_SECRET,value);}
export async function apiRoute(request,env){const recipient=env.CONTACT_EMAIL||"rortegarcia@gmail.com";if(request.method!=='POST')return json({error:'method'},405);if(request.headers.get('Origin')!==new URL(request.url).origin)return json({error:'origin'},403);if(!request.headers.get('Content-Type')?.includes('application/json'))return json({error:'type'},415);if(!env.RESEND_API_KEY||!env.REGISTRATION_SECRET)return json({error:'unavailable'},503);const raw=await request.text();if(raw.length>4096)return json({error:'size'},413);let input;try{input=JSON.parse(raw)}catch{return json({error:'invalid'},400)}
if(new URL(request.url).pathname==='/api/registration-status'){const parts=String(input.receipt||'').split('.');if(parts.length!==3||Number(parts[1])<Date.now()/1000||!/^[-a-z0-9]+$/.test(parts[0])||await hmac(env.REGISTRATION_SECRET,parts[0]+'.'+parts[1])!==parts[2])return json({error:'invalid'},403);const res=await api(env,'/emails/'+parts[0]);if(!res.ok)return json({status:'pending'},202);const data=await res.json();if(!data.to?.includes(recipient))return json({error:'invalid'},403);const delivered=['delivered','opened','clicked'].includes(data.last_event);const failed=['bounced','failed','complained','suppressed'].includes(data.last_event);return json({status:delivered?'delivered':failed?'failed':'pending',...(delivered?{paypal:env.PAYPAL_URL||'https://paypal.me/rosanaortega/30EUR'}:{})});}
const inquiry=new URL(request.url).pathname==='/api/inquiries';
const topics={portugues:'Portugués',espanol:'Español',taller:'Taller de lectura',materiales:'Productos lingüísticos',translation:'Traducción e interpretación',interpretation:'Interpretación',classes:'Clases de idiomas',equipment:'Alquiler de equipos de transmisión y recepción',information:'Información general',payment:'Consulta de pago'};
const message=String(input.message||'').trim();
const name=String(input.name||'').trim(),email=String(input.email||'').trim(),title=inquiry?topics[input.topic]:titles[input.workshop],reference=String(input.reference||'');if(message.length>3000||!title||!name||name.length>100||/[\r\n]/.test(name)||email.length>200||!/^\S+@[^\s@]+\.[^\s@]+$/.test(email)||input.consent!==true||!/^[-a-f0-9]{36}$/.test(reference)||input.honey)return json({error:'invalid'},400);
const key=await hmac(env.REGISTRATION_SECRET,JSON.stringify([reference,name,email,inquiry?input.topic:input.workshop,message,inquiry]));
const payload={from:env.RESEND_FROM||'Plataforma Português <onboarding@resend.dev>',to:[recipient],reply_to:email,subject:'Inscripción — '+title,text:['Nueva solicitud de inscripción', '', 'Nombre: '+name,'Correo: '+email,'Taller: '+title,'Importe: 30 EUR por las dos sesiones','Referencia: '+reference,'Consentimiento: aceptado','', 'PAGO PENDIENTE. Este correo registra la solicitud, no acredita el cobro.','PayPal se habilitará tras confirmarse la entrega de este correo.'].join('\n')};
if(inquiry){payload.subject='Solicitud de información — '+title;payload.text=['Nueva solicitud de información','Nombre: '+name,'Correo: '+email,'Interés: '+title,'Referencia: '+reference,'Consentimiento: aceptado','','Mensaje:',message||'(Sin mensaje adicional)'].join('\n');}
let res;for(let attempt=0;attempt<2;attempt++){res=await api(env,'/emails',payload,'workshop/'+key);if(res.ok||res.status<500&&res.status!==429)break;await new Promise(resolve=>setTimeout(resolve,1000));}if(!res.ok)return json({error:'send_failed'},502);const result=await res.json();if(!result.id)return json({error:'send_failed'},502);return json({status:'pending',receipt:await receipt(env,result.id)},202);}
export default{async fetch(request,env){const url=new URL(request.url);if(['/api/registrations','/api/registration-status','/api/inquiries'].includes(url.pathname)){try{return await apiRoute(request,env)}catch{return json({error:'unavailable'},503)}}if(!['GET','HEAD'].includes(request.method))return new Response('Method not allowed',{status:405});let p;try{p=decodeURIComponent(url.pathname)}catch{return new Response('Bad request',{status:400})}p=p==='/'?'/index.html':p.replace(/\/$/,'');const asset=assets[p]||assets[p+'.html'];if(!asset)return new Response('Página no encontrada',{status:404});return new Response(request.method==='HEAD'?null:Uint8Array.from(atob(asset[1]),c=>c.charCodeAt(0)),{headers:{'Content-Type':asset[0],'X-Content-Type-Options':'nosniff','Cache-Control':'no-cache'}});}};
